name: Auto Release

on:
  push:
    branches:
      - master
      - next
      - next-major
      - beta
      - alpha
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x"

jobs:
  release:
    uses: casbin-rs/semantic-release-action-rust/.github/workflows/release-binary.yml@master
    with:
      targets: |
        x86_64-unknown-linux-gnu
        x86_64-pc-windows-gnu
    secrets:
      cargo-registry-token: ${{ secrets.CARGO_TOKEN }}
